package io.github.orioncraftmc.flexkt.enums.css

import io.github.orioncraftmc.flexkt.traits.DefaultTrait

/**
 * The 'visibility' property specifies whether the boxes generated by an element are rendered.
 */
enum class CssVisibility(val visible: Boolean, val affectsLayout: Boolean) {

    /**
     * The generated box is visible.
     */
    VISIBLE(visible = true, affectsLayout = true),

    /**
     * The generated box is invisible (fully transparent, nothing is drawn), but still affects layout.
     */
    HIDDEN(visible = false, affectsLayout = true),

    /**
     * The generated box is invisible (fully transparent, nothing is drawn), and does not affect layout.
     */
    COLLAPSE(visible = false, affectsLayout = false);

    companion object : DefaultTrait<CssVisibility> {
        override val initial: CssVisibility = VISIBLE
    }
}